name: Python Formatting

on:
  push:
    branches:
      - "*"

jobs:
  format:
    name: Format Python Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install

      - name: Run Black
        run: poetry run black . --check

      - name: Commit changes if any
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git diff --exit-code; then
            echo "No changes detected."
          else
            echo "Changes detected. Committing changes..."
            git config --global user.name "github-actions"
            git config --global user.email "actions@github.com"
            git add .
            git commit -m "Apply code formatting with Black"
            git push origin HEAD
          fi
