# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install

    - name: Commit changes if any
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ poetry run black . --check > /dev/null ]; then
          echo "No changes detected."
        else
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          poetry run black .
          echo "Changes detected. Committing changes..."
          git add .
          git commit -m "Apply code formatting with Black"
          git push origin HEAD
        fi
    - name: Lint with flake8
      run: poetry run lint
    - name: Test with pytest
      run: poetry run pytest tests/
